### ISSUE TITLE
Kinect sdk가 있어야 합니다

### ISSUE THREAD

**Issue by jongfeel** [progsecu/Project-Kinect#1]
실제 kinect control 이 있는지와 상관 없이
관련 package가 필요한데...
NuGet에 있는 걸로 했는데도 class나 namespace를 못찾는 걸 봐서는
kinect v1인 거 같은데 확인 좀 해주세요.

**Comment by progsecu** [comment]
네 안그래도 업로드 중입니다.

**Comment by progsecu** [comment]
220MB정도라 업로드가 느리네요. 메인페이지 링크로 받으시는게 빠르실듯합니다.

**Comment by jongfeel** [comment]
제가 2년전에 Kinect 했었는데 그떄는 v2로 했었거든요.
어쨌든 kinect device 못찾는거 빼고는 build - run 은 동작되네요.
다음주에 리뷰 진행할 떄 "꼭" 들어오시면 좋습니다.

**Comment by progsecu** [comment]
네 저희 연구실이 가난한지 ㅎㅎ.

**Comment by progsecu** [comment]
네 저희 연구실이 가난한지 v1 뿐이라 ㅎㅎ.
